---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/tags
  label: Tags
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/snippets
  label: Snippets
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/lessons
  label: Lessons
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/dashboard
  label: Dashboard
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/courses
  label: Courses
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/contributors
  label: Contributors
  create: all
  match: "**/*"
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.78.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
